name: "Go CI (Reusable)"

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: false
        default: '1.25'

jobs:
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Run Linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: goinstall
          working-directory: .
          args: --timeout=5m

      - name: Run Unit Tests
        run: go test ./... -v
